language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
deploy:
  provider: heroku
  api_key: 8c564d6d-5864-4abb-a01b-5e6b599d2fd7
  app: baggrealty